-- 1
CREATE TABLE CYTATY AS SELECT * FROM ZTPD.CYTATY;

-- 2
SELECT AUTOR, TEKST 
FROM CYTATY
WHERE UPPER(TEKST) LIKE '%OPTYMISTA%'
    AND UPPER(TEKST) LIKE '%PESYMISTA%';

-- 3
CREATE INDEX idx_cytaty_tekst ON CYTATY(TEKST) 
INDEXTYPE IS CTXSYS.CONTEXT;

-- 4
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE CONTAINS(TEKST, 'optymista AND pesymista', 1) > 0;

-- 5
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE CONTAINS(TEKST, 'pesymista NOT optymista', 1) > 0;

-- 6
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE CONTAINS(TEKST, 'NEAR((optymista, pesymista), 3)', 1) > 0;

-- 7
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE CONTAINS(TEKST, 'NEAR((optymista, pesymista), 10)', 1) > 0;

-- 8
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE CONTAINS(TEKST, 'życi%', 1) > 0;

-- 9
SELECT AUTOR, TEKST, SCORE(1) AS DOPASOWANIE
FROM CYTATY 
WHERE CONTAINS(TEKST, 'życi%', 1) > 0;

-- 10
SELECT AUTOR, TEKST, SCORE(1) AS DOPASOWANIE
FROM CYTATY 
WHERE CONTAINS(TEKST, 'życi%', 1) > 0
ORDER BY SCORE(1) DESC
FETCH FIRST 1 ROW ONLY;

-- 11
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE CONTAINS(TEKST, '?probelm', 1) > 0;

-- 12
INSERT INTO CYTATY VALUES (
    39, 
    'Bertrand Russell', 
    'To smutne, że głupcy są tacy pewni siebie, a ludzie rozsądni tacy pełni wątpliwości.'
);
COMMIT;

-- 13
SELECT AUTOR, TEKST 
FROM CYTATY 
WHERE CONTAINS(TEKST, 'głupcy', 1) > 0;

-- 14
SELECT TOKEN_TEXT FROM DR$IDX_CYTATY_TEKST$I WHERE TOKEN_TEXT = 'GŁUPCY';

-- 15
DROP INDEX idx_cytaty_tekst;
CREATE INDEX idx_cytaty_tekst ON CYTATY(TEKST) INDEXTYPE IS CTXSYS.CONTEXT;

-- 17
DROP INDEX idx_cytaty_tekst;
DROP TABLE CYTATY;

-- 2.1
CREATE TABLE QUOTES AS SELECT * FROM ZTPD.QUOTES;

-- 2.2
CREATE INDEX idx_quotes_text ON QUOTES(TEXT) 
INDEXTYPE IS CTXSYS.CONTEXT;

-- 2.3
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'work', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '$work', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'working', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '$working', 1) > 0;

-- 2.4
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'it', 1) > 0;

-- 2.5
SELECT * FROM CTX_STOPLISTS;

-- 2.6
SELECT * FROM CTX_STOPWORDS WHERE SPW_STOPLIST = 'DEFAULT_STOPLIST';

-- 2.7
DROP INDEX idx_quotes_text;
CREATE INDEX idx_quotes_text ON QUOTES(TEXT) 
INDEXTYPE IS CTXSYS.CONTEXT 
PARAMETERS ('STOPLIST CTXSYS.EMPTY_STOPLIST');

-- 2.8
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'it', 1) > 0;

-- 2.9
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'fool AND humans', 1) > 0;

-- 2.10
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'fool AND computer', 1) > 0;

-- 2.11
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '(fool AND humans) WITHIN SENTENCE', 1) > 0;

-- 2.12
DROP INDEX idx_quotes_text;

-- 2.13
BEGIN
    CTX_DDL.CREATE_SECTION_GROUP('moje_sekcje', 'NULL_SECTION_GROUP');
    CTX_DDL.ADD_SPECIAL_SECTION('moje_sekcje', 'SENTENCE');
    CTX_DDL.ADD_SPECIAL_SECTION('moje_sekcje', 'PARAGRAPH');
END;
/

-- 2.14
CREATE INDEX idx_quotes_text ON QUOTES(TEXT) 
INDEXTYPE IS CTXSYS.CONTEXT 
PARAMETERS ('SECTION GROUP moje_sekcje STOPLIST CTXSYS.EMPTY_STOPLIST');

-- 2.15
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '(fool AND humans) WITHIN SENTENCE', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '(fool AND computer) WITHIN SENTENCE', 1) > 0;

-- 2.16
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'humans', 1) > 0;

-- 2.17
DROP INDEX idx_quotes_text;

BEGIN
    CTX_DDL.CREATE_PREFERENCE('moj_lekser', 'BASIC_LEXER');
    CTX_DDL.SET_ATTRIBUTE('moj_lekser', 'PRINTJOINS', '-');
END;
/

CREATE INDEX idx_quotes_text ON QUOTES(TEXT) 
INDEXTYPE IS CTXSYS.CONTEXT 
PARAMETERS ('LEXER moj_lekser SECTION GROUP moje_sekcje STOPLIST CTXSYS.EMPTY_STOPLIST');

-- 2.18
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'humans', 1) > 0;

-- 2.19
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'non\-humans', 1) > 0;

-- 2.20
DROP TABLE QUOTES;
BEGIN
    CTX_DDL.DROP_PREFERENCE('moj_lekser');
    CTX_DDL.DROP_SECTION_GROUP('moje_sekcje');
END;
/