-- ĆWICZENIE 1

-- A
CREATE TABLE FIGURY (
	ID number(1) PRIMARY KEY,
	KSZTALT MDSYS.SDO_GEOMETRY
)

SELECT * FROM FIGURY;

-- B
-- Circle
INSERT INTO FIGURY (ID, KSZTALT)
VALUES (
	1,
	MDSYS.SDO_GEOMETRY(
		2003, NULL, NULL,
		MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 4),
		MDSYS.SDO_ORDINATE_ARRAY(5, 7, 3, 5, 5, 3)
	)
)

-- Square
INSERT INTO FIGURY (ID, KSZTALT)
VALUES (
	2,
	MDSYS.SDO_GEOMETRY(
		2003, NULL, NULL,
		MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
		MDSYS.SDO_ORDINATE_ARRAY(1, 1, 5, 1, 5, 5, 1, 5)
	)
)

-- Corrected square (must be closed)
UPDATE FIGURY
SET KSZTALT = MDSYS.SDO_GEOMETRY(
		2003, NULL, NULL,
		MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
		MDSYS.SDO_ORDINATE_ARRAY(1, 1, 5, 1, 5, 5, 1, 5, 1, 1)
	)
WHERE ID = 2;

-- LINE
INSERT INTO FIGURY (ID, KSZTALT)
VALUES (
	3,
	MDSYS.SDO_GEOMETRY(
		2006, NULL, NULL,
		MDSYS.SDO_ELEM_INFO_ARRAY(1, 2, 1, 5, 2, 1, 9, 2, 2),
		MDSYS.SDO_ORDINATE_ARRAY(3, 2, 6, 2, 6, 2, 7, 3, 7, 3, 8, 2, 7, 1)
	)
)

SELECT ID, 
       SDO_UTIL.TO_WKTGEOMETRY(
           SDO_GEOM.SDO_ARC_DENSIFY(KSZTALT, 0.005, 'arc_tolerance=0.005')
       ) as GEOM_WKT
FROM FIGURY;

-- C
-- opened Square
INSERT INTO FIGURY (ID, KSZTALT)
VALUES (
	4,
	MDSYS.SDO_GEOMETRY(
		2003, NULL, NULL,
		MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
		MDSYS.SDO_ORDINATE_ARRAY(1, 1, 5, 1, 5, 5)
	)
)

SELECT ID, 
       SDO_UTIL.TO_WKTGEOMETRY(
           SDO_GEOM.SDO_ARC_DENSIFY(KSZTALT, 0.005, 'arc_tolerance=0.005')
       ) as GEOM_WKT
FROM FIGURY;

-- D
SELECT ID, SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.01)
FROM FIGURY
ORDER BY ID;

-- E
DELETE FROM FIGURY 
WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.01) != 'TRUE'

SELECT * FROM FIGURY;

COMMIT;
