-- ĆWICZENIE 1
-- A
INSERT INTO USER_SDO_GEOM_METADATA
VALUES (
'FIGURY',
'KSZTALT',
MDSYS.SDO_DIM_ARRAY(
 MDSYS.SDO_DIM_ELEMENT('X', 1, 8, 0.1),
 MDSYS.SDO_DIM_ELEMENT('Y', 1, 7, 0.1) ),
 NULL
);

-- B
SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000,8192,10,2,0)
FROM DUAL;

-- C
CREATE INDEX FIGURY_IDX
ON FIGURY(KSZTALT)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2; 

-- D
SELECT ID
FROM FIGURY
WHERE SDO_FILTER(KSZTALT,
SDO_GEOMETRY(2001,NULL,
 SDO_POINT_TYPE(3,3,NULL),
 NULL,NULL)) = 'TRUE';

-- E
SELECT ID
FROM FIGURY
WHERE SDO_RELATE(KSZTALT,
 SDO_GEOMETRY(2001,NULL,
 SDO_POINT_TYPE(3,3,NULL),
 NULL,NULL),
 'mask=ANYINTERACT') = 'TRUE';

-- ĆWICZENIE 2
-- A
SELECT 
	CITY_NAME AS MIASTO, 
	ROUND(SDO_NN_DISTANCE(1)) AS ODL
FROM MAJOR_CITIES
WHERE 
	(
	SDO_NN(
		GEOM,
		(
		SELECT GEOM FROM MAJOR_CITIES
		WHERE CITY_NAME = 'Warsaw'
		),
		'sdo_num_res=10',
		1
	) = 'TRUE'
	)
	AND
	CITY_NAME != 'Warsaw';

-- B
SELECT 
	CITY_NAME AS MIASTO
FROM MAJOR_CITIES
WHERE 
	SDO_WITHIN_DISTANCE(
		GEOM,
		(
		SELECT GEOM FROM MAJOR_CITIES
		WHERE CITY_NAME = 'Warsaw'
		),
		'distance = 100 unit=km'
	) = 'TRUE'
	AND
	CITY_NAME != 'Warsaw';

-- C
SELECT 
	mc.CITY_NAME AS KRAJ,
	mc.CNTRY_NAME AS MIASTO
FROM major_cities mc
WHERE SDO_RELATE(
	mc.GEOM, 
	(SELECT GEOM FROM country_boundaries WHERE CNTRY_NAME = 'Slovakia'), 
	'mask=INSIDE'
	) = 'TRUE';

-- D
SELECT
	cb.CNTRY_NAME AS PANSTWO,
	SDO_GEOM.SDO_DISTANCE(
		(SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME = 'Poland'),
		cb.GEOM,
		1,
		'unit=km'
	) AS ODL
FROM COUNTRY_BOUNDARIES cb
WHERE NOT SDO_RELATE(
	cb.GEOM, 
	(SELECT GEOM FROM country_boundaries WHERE CNTRY_NAME = 'Poland'), 
	'mask=TOUCH'
	) = 'TRUE'
	AND cb.CNTRY_NAME != 'Poland';


-- ĆWICZENIE 3
-- A
SELECT
	cb.CNTRY_NAME AS PANSTWO,
	SDO_GEOM.SDO_LENGTH(
		SDO_GEOM.SDO_INTERSECTION(
			(SELECT GEOM FROM country_boundaries WHERE CNTRY_NAME = 'Poland'),
			cb.GEOM,
			1
		),
		1,
		'unit=km'
	) AS ODLEGLOSC
FROM COUNTRY_BOUNDARIES cb
WHERE SDO_RELATE(
	cb.GEOM, 
	(SELECT GEOM FROM country_boundaries WHERE CNTRY_NAME = 'Poland'), 
	'mask=TOUCH'
	) = 'TRUE'
	AND cb.CNTRY_NAME != 'Poland';

-- B
SELECT CNTRY_NAME
FROM COUNTRY_BOUNDARIES cb
WHERE 
	SDO_GEOM.SDO_AREA(cb.GEOM) = 
	(SELECT MAX(SDO_GEOM.SDO_AREA(GEOM)) FROM COUNTRY_BOUNDARIES)

-- C
SELECT SDO_GEOM.SDO_AREA(SDO_AGGR_MBR(mc.geom))
FROM MAJOR_CITIES mc
WHERE CNTRY_NAME = 'Poland' AND CITY_NAME IN ('Warsaw', 'Lodz');

-- D
SELECT 
    CONCAT('200', MOD(SDO_GEOM.SDO_UNION(cb.GEOM, mc.GEOM, 0.05).SDO_GTYPE, 100)) AS GTYPE
FROM 
    COUNTRY_BOUNDARIES cb, 
    MAJOR_CITIES mc
WHERE 
    cb.CNTRY_NAME = 'Poland' 
    AND mc.CITY_NAME = 'Prague';

-- E
SELECT mc.CITY_NAME, cb.CNTRY_NAME
FROM COUNTRY_BOUNDARIES cb
JOIN MAJOR_CITIES mc
ON cb.CNTRY_NAME = mc.CNTRY_NAME
ORDER BY SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(cb.GEOM, 1), mc.GEOM) ASC
FETCH FIRST 1 ROWS ONLY;

-- F
WITH RIVERS_LENGTHS AS (
	SELECT 
		r.name AS NAME, 
		ROUND(
			SUM(
				SDO_GEOM.SDO_LENGTH(
					SDO_GEOM.SDO_INTERSECTION(
						(SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME = 'Poland'), 
						r.GEOM, 
						0.1
					)
				)
			) 
		) AS DLUGOSC
	from rivers R
	GROUP BY name
)
SELECT NAME, DLUGOSC
FROM RIVERS_LENGTHS
WHERE DLUGOSC IS NOT NULL;