-- Ćwiczenie 1
SELECT LPAD('-',2*(LEVEL-1),'|-') || T.OWNER||'.'||T.TYPE_NAME||' (FINAL:'||T.FINAL||
', INSTANTIABLE:'||T.INSTANTIABLE||', ATTRIBUTES:'||T.ATTRIBUTES||', METHODS:'||T.METHODS||')'
FROM ALL_TYPES T
START WITH T.TYPE_NAME = 'ST_GEOMETRY'
CONNECT BY PRIOR T.TYPE_NAME = T.SUPERTYPE_NAME
 AND PRIOR T.OWNER = T.OWNER;
 
SELECT DISTINCT M.METHOD_NAME
FROM ALL_TYPE_METHODS M
WHERE M.TYPE_NAME LIKE 'ST_POLYGON'
AND M.OWNER = 'MDSYS'
ORDER BY 1;

CREATE TABLE MYST_MAJOR_CITIES(
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

INSERT INTO MYST_MAJOR_CITIES
SELECT FIPS_CNTRY, CITY_NAME, ST_POINT(GEOM) FROM ZTPD.MAJOR_CITIES;

SELECT * FROM MYST_MAJOR_CITIES;

-- Ćwiczenie 2
INSERT INTO MYST_MAJOR_CITIES
VALUES (
    'PL',
    'Szczyrk', 
    ST_POINT(19.036107, 49.718655, 8307)
);

-- Ćwiczenie 3
CREATE TABLE MYST_COUNTRY_BOUNDARIES(
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
);

INSERT INTO MYST_COUNTRY_BOUNDARIES
SELECT FIPS_CNTRY, CNTRY_NAME, ST_MULTIPOLYGON(GEOM) FROM COUNTRY_BOUNDARIES;

SELECT * FROM MYST_COUNTRY_BOUNDARIES;

SELECT A.STGEOM.ST_GEOMETRYTYPE() AS TYP_OBIEKTU, COUNT(*) AS ILE
FROM MYST_COUNTRY_BOUNDARIES A
GROUP BY A.STGEOM.ST_GEOMETRYTYPE();

SELECT A.STGEOM.ST_ISSIMPLE()
FROM MYST_COUNTRY_BOUNDARIES A;

-- Ćwiczenie 4
SELECT B.CNTRY_NAME, COUNT(C.CITY_NAME) AS LICZBA_MIAST
FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE B.STGEOM.ST_CONTAINS(C.STGEOM) = 1
GROUP BY B.CNTRY_NAME;

SELECT A.CNTRY_NAME, B.CNTRY_NAME
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Czech Republic' AND B.STGEOM.ST_TOUCHES(A.STGEOM) = 1;

SELECT DISTINCT A.CNTRY_NAME, R.NAME
FROM MYST_COUNTRY_BOUNDARIES A, RIVERS R
WHERE A.CNTRY_NAME = 'Czech Republic' AND A.STGEOM.ST_CROSSES(ST_LINESTRING(R.GEOM)) = 1;

SELECT A.STGEOM.ST_AREA() + B.STGEOM.ST_AREA() AS POWIERZCHNIA
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE A.CNTRY_NAME = 'Czech Republic' 
AND B.CNTRY_NAME = 'Slovakia';

SELECT A.STGEOM.ST_DIFFERENCE(ST_MULTIPOLYGON(B.GEOM)) AS WEGRY_BEZ_BALATONU
FROM MYST_COUNTRY_BOUNDARIES A, WATER_BODIES B
WHERE A.CNTRY_NAME = 'Hungary' 
AND B.NAME = 'Balaton';

-- Ćwiczenie 5
EXPLAIN PLAN FOR
SELECT B.CNTRY_NAME AS NAME, COUNT(*) AS LICZBA_MIAST
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland'
AND SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
GROUP BY(B.CNTRY_NAME);

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES (
    'MYST_MAJOR_CITIES',
    'STGEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', -180, 180, 1),
        SDO_DIM_ELEMENT('Y', -90, 90, 1)
        ),
    8307
);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES (
    'MYST_COUNTRY_BOUNDARIES',
    'STGEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', -180, 180, 1),
        SDO_DIM_ELEMENT('Y', -90, 90, 1)
    ),
    8307
);

CREATE INDEX CITIES_IDX
ON MYST_MAJOR_CITIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

CREATE INDEX COUNTRIES_IDX
ON MYST_COUNTRY_BOUNDARIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

SELECT B.CNTRY_NAME AS NAME, COUNT(*) AS LICZBA_MIAST
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland'
AND SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
GROUP BY(B.CNTRY_NAME);

EXPLAIN PLAN FOR
SELECT B.CNTRY_NAME AS NAME, COUNT(*) AS LICZBA_MIAST
FROM MYST_MAJOR_CITIES C, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Poland'
AND SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
GROUP BY(B.CNTRY_NAME);

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);