-- Ćwiczenie 1
-- A
CREATE TABLE S6_LRS (
    GEOM SDO_GEOMETRY
);

-- B
INSERT INTO S6_LRS
    SELECT SR.GEOM
    FROM STREETS_AND_RAILROADS SR, MAJOR_CITIES C
    WHERE SDO_RELATE(SR.GEOM, SDO_GEOM.SDO_BUFFER(C.GEOM, 10, 1, 'unit=km'), 'MASK=ANYINTERACT') = 'TRUE'
    AND C.CITY_NAME = 'Koszalin';
    
-- C
SELECT SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km') DISTANCE, ST_LINESTRING(GEOM).ST_NUMPOINTS() ST_NUMPOINTS
FROM S6_LRS;

-- D
UPDATE S6_LRS SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681);

-- E
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('S6_LRS','GEOM',
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
        MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
        MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) 
        ),
        8307
    );
    
-- F
CREATE INDEX lrs_routes_idx ON S6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- Ćwiczenie 2
-- A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
FROM S6_LRS;

-- B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
FROM S6_LRS;

-- C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150
FROM S6_LRS;

-- D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPPED
FROM S6_LRS;

-- E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(
        a.GEOM, 
        SDO_LRS.FIND_MEASURE(a.GEOM, b.GEOM)
    ) AS WJAZD_NA_S6
FROM S6_LRS a, MAJOR_CITIES b
WHERE b.CITY_NAME = 'Slupsk';

-- F
SELECT 
  SDO_GEOM.SDO_LENGTH(
    SDO_LRS.OFFSET_GEOM_SEGMENT(
      S6.GEOM,
      50,
      200,
      50,
      0.01,
      'unit=m'
    ), 
    1,
    'unit=km'
  ) * 1000000 AS KOSZT

FROM S6_LRS S6;